import { mkdirSync, readFileSync, writeFileSync, renameSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { SetupStateSchema, defaultSetupState, type SetupState } from './schema.js';

const PROGRESS_DIR = '.superintendent';
const PROGRESS_FILE = 'setup-progress.json';

function progressPath(cwd: string): string {
  return join(cwd, PROGRESS_DIR, PROGRESS_FILE);
}

export function loadProgress(cwd: string): SetupState {
  const path = progressPath(cwd);
  if (!existsSync(path)) {
    return defaultSetupState();
  }
  try {
    const raw = readFileSync(path, 'utf-8');
    const parsed = JSON.parse(raw);
    const validated = SetupStateSchema.safeParse(parsed);
    return validated.success ? validated.data : defaultSetupState();
  } catch {
    return defaultSetupState();
  }
}

export function saveProgress(cwd: string, state: SetupState): void {
  const dir = join(cwd, PROGRESS_DIR);
  mkdirSync(dir, { recursive: true });
  const path = progressPath(cwd);
  writeFileSync(path, JSON.stringify(state, null, 2), 'utf-8');
}

export function writeEnvFileAtomic(cwd: string, state: SetupState): void {
  const envPath = join(cwd, '.env');
  const tmpPath = join(cwd, '.env.tmp');

  const lines: string[] = [
    '# Auto-generated by `npm run setup`. Run `npm run doctor` to re-validate.',
    '',
  ];

  const order: (keyof SetupState)[] = [
    'LINEAR_WORKSPACE_SLUG',
    'LINEAR_CLIENT_ID',
    'LINEAR_CLIENT_SECRET',
    'LINEAR_PERSONAL_TOKEN',
    'LINEAR_TEAM_ID',
    'LINEAR_PROJECT_ID',
    'ANTHROPIC_API_KEY',
    'ANTHROPIC_MODEL',
    'GITHUB_REPO',
    'AGENTS_WORK_DIR',
    'AGENTS_MAX_CONCURRENT',
    'AGENTS_MAX_CODE_EXECUTORS',
    'AGENTS_TIMEOUT_MINUTES',
    'AGENTS_MAX_RETRIES',
    'DAEMON_POLL_INTERVAL_SECONDS',
  ];

  for (const key of order) {
    const value = state[key];
    if (value === undefined || value === '' || value === null) continue;
    lines.push(`${key}=${value}`);
  }

  writeFileSync(tmpPath, lines.join('\n') + '\n', 'utf-8');
  renameSync(tmpPath, envPath);
}
